//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGClubDeportivo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenamiento
    {
        public string id_entrenamiento { get; set; }
        public string primerdia { get; set; }
        public string segundodia { get; set; }
        public string primerhorario { get; set; }
        public string segundohorario { get; set; }
        public string ci_jugador { get; set; }
        public int id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
