//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGClubDeportivo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiaPrecios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuiaPrecios()
        {
            this.Mensualidades = new HashSet<Mensualidades>();
        }
    
        public int id { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensualidades> Mensualidades { get; set; }
    }
}
