//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGClubDeportivo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int id_horario { get; set; }
        public string hora { get; set; }
        public string dia { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string ci_admin { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
