//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGClubDeportivo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public string ci_jugador { get; set; }
        public string nom_jugador { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string ci_secretaria { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Secretaria Secretaria { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
