//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGClubDeportivo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador_cat
    {
        public int id_asignacion { get; set; }
        public string ci_jugador { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Jugador Jugador { get; set; }
    }
}
