//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGClubDeportivo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensualidades
    {
        public int id { get; set; }
        public string Mes { get; set; }
        public string Estado { get; set; }
        public string ciJugador { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
